Add baggage and client_generated_trip
trip-ninja-inc/trip_ninja_api_docs pull request #5
Opened 2019-11-26 20:29 UTC by Iceman997

2019-11-26 20:36 UTC, niloufarmp requested changes

2019-11-26 20:36 UTC, niloufarmp commented on tn_api_spec.yml
> +            trip_id
I saw in Kalenshi comments that an empty segment_id list is also required?

2019-11-28 14:42 UTC, mcclymont-k approved these changes

2019-11-28 14:49 UTC, johna-tripninja approved these changes

2019-11-28 15:16 UTC, niloufarmp approved these changes

2019-11-28 15:20 UTC, merged