feature/update-for-rooms-and-travellers-on-booking
trip-ninja-inc/trip_ninja_api_docs pull request #77
Opened 2021-06-22 17:06 UTC by mcclymont-k

**DESCRIPTION**
Update for the booking details response on this MCFS PR.

**TESTING**
1. Compare with the response from MCFS on that PR ☝️

2021-06-22 17:11 UTC, trip-ninja-inc commented
Task linked: [CU-3ytqf6 Number of rooms not saved in hotel booking](https://app.clickup.com/t/3ytqf6)

2021-06-23 13:53 UTC, andrescollart requested changes

2021-06-23 13:53 UTC, andrescollart commented on tn_api_pricing_booking_spec.yml
> +                      description: Currency to make the search in.
Currency the booking was made in, not the search at this stage.

2021-06-23 13:54 UTC, mcclymont-k commented on tn_api_pricing_booking_spec.yml
> +                      description: Currency to make the search in.
```suggestion
                      description: Currency the booking was made in.
```

2021-06-23 14:08 UTC, andrescollart approved these changes

2021-07-05 13:24 UTC, merged